#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Check Prettier standards
yarn check-format ||
	(
		printf '\n🤢🤮🤢🤮 Its F**KING RAW 🤢🤮🤢🤮\n'
		false
	)

# Check ESLint Standards
yarn lint ||
	(
		printf '\n😤🏀👋😤 Get that weak s**t out of here 😤🏀👋😤\n'
		false
	)

# Check tsconfig standards
yarn check-types ||
	(
		printf '\n🤡😂❌🤡 Failed Type check 🤡😂❌🤡\n'
		false
	)

yarn build ||
	(
		printf '\n❌👷🔨❌ Better call Bob ❌👷🔨❌\n'
		false
	)
