name: "Tests: E2E"

on:
  pull_request:
    branches: [main, dev]

env:
  DATABASE_URL: mysql://root:Passw0rd@localhost:3309/melvin

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Spin up database docker
        run: yarn db-up

      - name: Wait for the database to start
        run: wget -qO- https://raw.githubusercontent.com/eficode/wait-for/$WAIT_FOR_VERSION/wait-for | sh -s -- localhost:3309 -- echo "Database is up"
        env:
          WAIT_FOR_VERSION: 4df3f9262d84cab0039c07bf861045fbb3c20ab7 # v2.2.3

      - name: Initialise database
        run: yarn db-migrate-dev

      - name: Run tests
        run: yarn test:e2e
