name: "E2E Tests"

on:
  pull_request:
    branches: [main, dev]

env:
  DATABASE_URL: mysql://root:Passw0rd@localhost:3309/melvin
  NEXTAUTH_URL: "http://localhost:3000"
  NEXTAUTH_SECRET: "7893onvi808u7q1ounbv"
  GOOGLE_ID: ""
  GOOGLE_SECRET: ""
  EMAIL_SERVER: ""
  EMAIL_FROM: ""

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Spin up database docker
        run: pnpm db:up

      - name: Sleep for 15 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: "15s"

      - name: Initialise database
        run: pnpm prisma:dev

      - name: Run tests
        run: pnpm test:e2e
